[theme]
primaryColor = "#193c32"
backgroundColor = "#f3f2f3"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e5546"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
